export interface Personnel {
  role: string;
  name: string;
}

export interface F1Team {
  id: string;
  name: string;
  fullName: string;
  engine: string;
  color: string;
  textOnColor: "black" | "white";
  hq: string;
  country: string;
  countryCode: string;
  coords: string;
  founded: number;
  chassis: string;
  drivers: string[];
  principal: string;
  personnel: Personnel[];
  championships: { drivers: number; constructors: number };
  description: string;
  website: string;
  constructorId: string;
}

export const TEAMS_2026: F1Team[] = [
  {
    id: "mclaren",
    constructorId: "mclaren",
    name: "McLaren",
    fullName: "McLaren Formula 1 Team",
    engine: "Mercedes",
    color: "#ff8000ff",
    textOnColor: "black",
    hq: "Woking, Surrey",
    country: "United Kingdom",
    countryCode: "gb",
    coords: "51.3168°N  0.5606°W",
    founded: 1963,
    chassis: "MCL39",
    drivers: ["Lando Norris", "Oscar Piastri"],
    principal: "Andrea Stella",
    personnel: [
      { role: "CEO", name: "Zak Brown" },
      { role: "Team Principal", name: "Andrea Stella" },
      { role: "Technical Director", name: "Neil Houldey" },
      { role: "Chief Designer", name: "Rob Marshall" },
      { role: "Chief Engineer", name: "Andrew Sherrill" },
    ],
    championships: { drivers: 12, constructors: 9 },
    description: "2024 Constructors' Champions. The papaya warriors are back — fast, fearless, and hungry for more.",
    website: "mclaren.com",
  },
  {
    id: "mercedes",
    constructorId: "mercedes",
    name: "Mercedes",
    fullName: "Mercedes-AMG PETRONAS F1 Team",
    engine: "Mercedes",
    color: "#48c4b1ff",
    textOnColor: "black",
    hq: "Brackley, Northamptonshire",
    country: "United Kingdom",
    countryCode: "gb",
    coords: "52.0333°N  1.1500°W",
    founded: 2010,
    chassis: "W17",
    drivers: ["George Russell", "Kimi Antonelli"],
    principal: "Toto Wolff",
    personnel: [
      { role: "Team Principal & CEO", name: "Toto Wolff" },
      { role: "Technical Director", name: "Loic Serra" },
      { role: "Chief Designer", name: "John Owen" },
      { role: "Chief Engineer", name: "Andrew Shovlin" },
      { role: "Head of Aerodynamics", name: "Mike Elliott" },
    ],
    championships: { drivers: 9, constructors: 8 },
    description: "Eight consecutive Constructors' titles. The silver dynasty rebuilds around Russell and the next generation.",
    website: "mercedesamgf1.com",
  },
  {
    id: "ferrari",
    constructorId: "ferrari",
    name: "Ferrari",
    fullName: "Scuderia Ferrari HP",
    engine: "Ferrari",
    color: "#E8002D",
    textOnColor: "white",
    hq: "Maranello, Emilia-Romagna",
    country: "Italy",
    countryCode: "it",
    coords: "44.5318°N  10.8638°E",
    founded: 1950,
    chassis: "SF-25",
    drivers: ["Charles Leclerc", "Lewis Hamilton"],
    principal: "Fred Vasseur",
    personnel: [
      { role: "Team Principal & CEO", name: "Fred Vasseur" },
      { role: "Technical Director", name: "Enrico Cardile" },
      { role: "Head of Power Unit", name: "Enrico Gualtieri" },
      { role: "Chief Designer", name: "Diego Tondi" },
      { role: "Head of Race Ops", name: "Inaki Rueda" },
    ],
    championships: { drivers: 15, constructors: 16 },
    description: "The Prancing Horse. The most storied name in motorsport. Hamilton joins Leclerc. The dream partnership begins.",
    website: "ferrari.com/formula1",
  },
  {
    id: "red_bull",
    constructorId: "red_bull",
    name: "Red Bull",
    fullName: "Oracle Red Bull Racing",
    engine: "Ford RBPT",
    color: "#000044ff",
    textOnColor: "white",
    hq: "Milton Keynes, Buckinghamshire",
    country: "United Kingdom",
    countryCode: "gb",
    coords: "52.0406°N  0.7594°W",
    founded: 2005,
    chassis: "RB21",
    drivers: ["Max Verstappen", "Isack Hadjar"],
    principal: "Christian Horner",
    personnel: [
      { role: "Team Principal", name: "Christian Horner" },
      { role: "Technical Director", name: "Pierre Waché" },
      { role: "Head of Strategy", name: "Hannah Schmitz" },
      { role: "Chief Engineer", name: "Paul Monaghan" },
    ],
    championships: { drivers: 6, constructors: 6 },
    description: "Four-time constructors' champions. Verstappen's dynasty. New Ford works partnership shapes the 2026 power unit era.",
    website: "redbullracing.com",
  },
  {
    id: "aston_martin",
    constructorId: "aston_martin",
    name: "Aston Martin",
    fullName: "Aston Martin Aramco F1 Team",
    engine: "Honda RBPT",
    color: "#229971",
    textOnColor: "white",
    hq: "Silverstone, Northamptonshire",
    country: "United Kingdom",
    countryCode: "gb",
    coords: "52.0786°N  1.0169°W",
    founded: 2021,
    chassis: "AMR25",
    drivers: ["Fernando Alonso", "Lance Stroll"],
    principal: "Mike Krack",
    personnel: [
      { role: "Team Principal", name: "Mike Krack" },
      { role: "Technical Director", name: "Dan Fallows" },
      { role: "Chief Aero Officer", name: "Eric Blandin" },
      { role: "Head of Vehicle Perf", name: "Tom McCullough" },
    ],
    championships: { drivers: 0, constructors: 0 },
    description: "British Racing Green reborn. New Silverstone campus. Honda works power. Alonso hunting a third title.",
    website: "astonmartinf1.com",
  },
  {
    id: "alpine",
    constructorId: "alpine",
    name: "Alpine",
    fullName: "BWT Alpine F1 Team",
    engine: "Mercedes",
    color: "#0093CC",
    textOnColor: "white",
    hq: "Enstone, Oxfordshire",
    country: "United Kingdom",
    countryCode: "gb",
    coords: "51.9667°N  1.4500°W",
    founded: 2021,
    chassis: "A525",
    drivers: ["Pierre Gasly", "Jack Doohan"],
    principal: "Oliver Oakes",
    personnel: [
      { role: "Team Principal", name: "Oliver Oakes" },
      { role: "Technical Director", name: "David Sanchez" },
      { role: "Chief Race Engineer", name: "Ciaron Pilbeam" },
    ],
    championships: { drivers: 2, constructors: 0 },
    description: "Tricolore ambition. French soul, British base. Oakes' youth revolution battles for midfield supremacy.",
    website: "alpinecars.com/f1",
  },
  {
    id: "williams",
    constructorId: "williams",
    name: "Williams",
    fullName: "Williams Racing",
    engine: "Mercedes",
    color: "#0545d9",
    textOnColor: "white",
    hq: "Grove, Oxfordshire",
    country: "United Kingdom",
    countryCode: "gb",
    coords: "51.6148°N  1.4378°W",
    founded: 1977,
    chassis: "FW47",
    drivers: ["Alex Albon", "Carlos Sainz"],
    principal: "James Vowles",
    personnel: [
      { role: "Team Principal & CEO", name: "James Vowles" },
      { role: "Chief Designer", name: "Pat Fry" },
      { role: "Head of Perf Eng", name: "Dave Robson" },
    ],
    championships: { drivers: 7, constructors: 9 },
    description: "The sleeping giant stirs. Vowles' rebuild bears fruit. Sainz's arrival signals serious intent from Grove.",
    website: "williamsf1.com",
  },
  {
    id: "haas",
    constructorId: "haas",
    name: "Haas",
    fullName: "MoneyGram Haas F1 Team",
    engine: "Ferrari",
    color: "#B6BABD",
    textOnColor: "black",
    hq: "Kannapolis, North Carolina",
    country: "United States",
    countryCode: "us",
    coords: "35.5001°N  80.6215°W",
    founded: 2016,
    chassis: "VF-25",
    drivers: ["Oliver Bearman", "Esteban Ocon"],
    principal: "Ayao Komatsu",
    personnel: [
      { role: "Team Principal", name: "Ayao Komatsu" },
      { role: "Technical Director", name: "Simone Resta" },
      { role: "Head of Race Eng", name: "Peter McCool" },
    ],
    championships: { drivers: 0, constructors: 0 },
    description: "America's only team. Bearman and Ocon lead Komatsu's next chapter. Ferrari power. Fighting spirit.",
    website: "haasf1team.com",
  },
  {
    id: "racing_bulls",
    constructorId: "rb",
    name: "Racing Bulls",
    fullName: "Visa CashApp RB Formula One Team",
    engine: "Ford RBPT",
    color: "#3367eaff",
    textOnColor: "white",
    hq: "Faenza, Emilia-Romagna",
    country: "Italy",
    countryCode: "it",
    coords: "44.2853°N  11.8836°E",
    founded: 2006,
    chassis: "VCARB 02",
    drivers: ["Arvid Lindblad", "Liam Lawson"],
    principal: "Laurent Mekies",
    personnel: [
      { role: "Team Principal", name: "Laurent Mekies" },
      { role: "Technical Director", name: "Jody Eggington" },
      { role: "Head of Aerodynamics", name: "Brendan Gilhome" },
    ],
    championships: { drivers: 0, constructors: 0 },
    description: "Italian roots, Red Bull DNA. The academy's finest graduate pipeline. Tsunoda and Hadjar chase stardom.",
    website: "visacashapprb.com",
  },
  {
    id: "audi",
    constructorId: "sauber",
    name: "Audi",
    fullName: "Audi F1 Team",
    engine: "Audi",
    color: "#C00F0C",
    textOnColor: "white",
    hq: "Hinwil, Canton of Zurich",
    country: "Switzerland",
    countryCode: "ch",
    coords: "47.2946°N  8.8373°E",
    founded: 2026,
    chassis: "A26",
    drivers: ["Nico Hülkenberg", "Gabriel Bortoleto"],
    principal: "Mattia Binotto",
    personnel: [
      { role: "CEO & Team Principal", name: "Mattia Binotto" },
      { role: "Technical Director", name: "Andreas Roos" },
      { role: "Head of Chassis", name: "Luca Furbatto" },
      { role: "Head of Power Unit", name: "Adam Baker" },
    ],
    championships: { drivers: 0, constructors: 0 },
    description: "The four rings enter Formula One. Full works program. Hülkenberg leads Audi's grand return to top-tier motorsport.",
    website: "audisport.com/f1",
  },
  {
    id: "cadillac",
    constructorId: "cadillac",
    name: "Cadillac",
    fullName: "Cadillac F1 Team",
    engine: "Ferrari",
    color: "#B8960C",
    textOnColor: "black",
    hq: "Mooresville, North Carolina",
    country: "United States",
    countryCode: "us",
    coords: "35.5773°N  80.8092°W",
    founded: 2026,
    chassis: "GMGP-01",
    drivers: ["Sergio Pérez", "Valtteri Bottas"],
    principal: "Jeff Dickson",
    personnel: [
      { role: "Team Principal", name: "Jeff Dickson" },
      { role: "Technical Director", name: "Matt Borland" },
      { role: "Chief Operating Officer", name: "Robert Fernley" },
      { role: "Head of Aerodynamics", name: "Eric Blandin" },
    ],
    championships: { drivers: 0, constructors: 0 },
    description: "GM's triumphant return to Formula 1. America's second team — Andretti heritage, Cadillac identity, Ferrari power. The 11th team is here.",
    website: "cadillacf1.com",
  },
];

export const getTeamById = (id: string) =>
  TEAMS_2026.find(t => t.id === id || t.constructorId === id);
